name: Gradle CI

on:
  - push

jobs:
  build:

    defaults:
      run:
        working-directory: vanilla

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: gradle/wrapper-validation-action@v1

      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          cache-read-only: false
