name: Build Vanilla

on:
  push:
    paths:
      - vanilla/**

env:
  WORKING_DIRECTORY: ${{ github.workspace }}/vanilla

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}

    steps:

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: gradle/wrapper-validation-action@v1

      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: ${{ env.WORKING_DIRECTORY }}
          cache-read-only: false
